--[[
    Copyright (C) 2023-2026 GurliGebis

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
]]

local BattlePetCompletionist = LibStub("AceAddon-3.0"):GetAddon("BattlePetCompletionist")
if not BattlePetCompletionist then
    return
end

local DataModule = BattlePetCompletionist:GetModule("DataModule")

-- PLEASE DO NOT CHANGE THIS FILE DIRECTLY - UPDATE THE JSON FILE IN GIT AND CREATE A PULL REQUEST INSTEAD --
-- THIS FILE IS GENERATED BY RUNNING THE Update-PetData.ps1 SCRIPT. --

local petData = {[14]={[277]="317413"},[15]={[277]="395471"},[17]={[266]="419370",[309]="419370"},[23]={[286]="130660",[310]="640154"},[25]={[266]="597574",[291]="336492",[309]="597574"},[26]={[277]="316440",[310]="355674"},[32]={[277]="430354"},[36]={[266]="778563",[277]="652326",[287]="548226",[309]="778563"},[37]={[319]="318500"},[47]={[266]="324708",[309]="324708"},[49]={[266]="342701",[309]="342701"},[50]={[266]="366466",[301]="760666",[309]="366466",[310]="602562"},[51]={[310]="651624"},[56]={[277]="537353"},[62]={[220]="508180572338"},[80]={[341]="540350",[342]="540350"},[83]={[306]="598514"},[84]={[270]="646768",[272]="646768",[289]="560550",[292]="530742",[320]="646768",[321]="651333"},[85]={[267]="532488",[270]="482756",[272]="482756",[289]="580576",[320]="482756",[321]="545778",[337]="526778"},[87]={[270]="366846",[272]="366846",[292]="616418",[320]="366846",[337]="336666"},[88]={[267]="450386",[270]="376628",[272]="376628",[320]="376628"},[89]={[270]="646376",[272]="646376",[292]="566318",[320]="646376"},[90]={[267]="620608",[270]="696434",[272]="696434",[319]="678806",[320]="696434"},[103]={[270]="536706",[272]="536706",[292]="404392",[320]="536706"},[110]={[270]="782850",[272]="782850",[320]="782850"},[111]={[270]="586466",[272]="586466",[308]="748478",[320]="586466"},[198]={[259]="428452",[260]="428452"},[207]={[265]="554140",[279]="612226",[293]="546483"},[210]={[310]="425241",[333]="426716"},[241]={[267]="766494",[277]="043296",[292]="786770",[293]="331388"},[244]={[293]="463354"},[245]={[271]="546810726626",[278]="546810726626",[293]="444388"},[249]={[264]="498549",[293]="658331"},[266]={[267]="700286"},[337]={[307]="612814"},[338]={[317]="446886",[318]="448866"},[407]={[330]="482694",[335]="482694",[338]="482692",[339]="482694",[340]="526866",[343]="482694"},[627]={[296]="318226320222320236322248",[298]="314230316244318224324226324246332220"},[1165]={[323]="562314"}}

DataModule:RegisterPetData(petData)
