--[[
    Copyright (C) 2023 GurliGebis

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
]]

local BattlePetCompletionist = LibStub("AceAddon-3.0"):GetAddon("BattlePetCompletionist")
if not BattlePetCompletionist then
    return
end

local DataModule = BattlePetCompletionist:GetModule("DataModule")

-- PLEASE DO NOT CHANGE THIS FILE DIRECTLY - UPDATE THE JSON FILE IN GIT AND CREATE A PULL REQUEST INSTEAD --
-- THIS FILE IS GENERATED BY RUNNING THE Update-PetData.ps1 SCRIPT. --

local petData = {[1]={[153]="412184",[166]="404178"},[10]={[179]="620390626376630372"},[27]={[153]="552378",[166]="562378"},[37]={[162]="318508"},[50]={[168]="282760",[179]="268736268768274776"},[71]={[179]="510292518284522274"},[83]={[179]="622366"},[84]={[189]="622692"},[85]={[166]="506736",[170]="582507",[179]="510698512688520688",[191]="526778"},[87]={[166]="198532",[170]="580413",[179]="300632",[191]="336666"},[88]={[175]="724232730238732224",[179]="408552410560414570"},[89]={[179]="412430"},[90]={[162]="678076",[189]="710472"},[94]={[142]="448716",[143]="448718",[144]="448714",[179]="540510"},[97]={[179]="204542"},[102]={[146]="412358506326",[167]="178512"},[103]={[138]="294336300332",[140]="294338300344302350306336",[141]="294336298348300338308340",[179]="518444680624"},[108]={[132]="678797",[149]="538722",[163]="386128",[164]="386128",[173]="386128",[174]="386128",[186]="642662"},[109]={[136]="434292",[137]="434292",[139]="434292",[145]="434292",[179]="322648328664338638"},[110]={[179]="886498"},[111]={[157]="748478",[159]="748478",[179]="280466282480488316492330494308496312496326500318526500552392552790552802582468586578634404"},[210]={[156]="426716",[168]="428714430716",[169]="426716",[183]="426716"},[333]={[165]="508516"},[338]={[172]="470906"},[376]={[158]="530520532510538498554494582462582490584440584478598446646456704440706438714398716384718426720412726384742378748368752364802364806396"},[627]={[179]="502246"},[998]={[179]="622466682396"}}

DataModule:RegisterPetData(petData)
