--[[
    Copyright (C) 2023 GurliGebis

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
]]

local BattlePetCompletionist = LibStub("AceAddon-3.0"):GetAddon("BattlePetCompletionist")
if not BattlePetCompletionist then
    return
end

local DataModule = BattlePetCompletionist:GetModule("DataModule")

-- PLEASE DO NOT CHANGE THIS FILE DIRECTLY - UPDATE THE JSON FILE IN GIT AND CREATE A PULL REQUEST INSTEAD --
-- THIS FILE IS GENERATED BY RUNNING THE Update-PetData.ps1 SCRIPT. --

local petData = {[1]={[153]="412184",[166]="404178"},[27]={[153]="552378",[166]="562378"},[37]={[162]="318508"},[84]={[189]="622692"},[85]={[166]="506736",[170]="582507",[191]="526778"},[87]={[166]="198532",[170]="580413",[191]="336666"},[90]={[162]="678076",[189]="710472"},[94]={[142]="448716",[143]="448716",[144]="448714"},[102]={[146]="412358506326",[167]="178512"},[103]={[138]="294332304338306346",[140]="300342",[141]="302342"},[108]={[132]="678797",[149]="538722",[163]="386128",[164]="386128",[173]="386128",[174]="386128",[186]="642662"},[109]={[136]="434292",[137]="434292",[139]="434292",[145]="434292"},[111]={[157]="748478",[158]="748478",[159]="748478"},[210]={[130]="426716",[156]="426716",[168]="426716",[169]="426716",[183]="426716"},[333]={[165]="508516"},[338]={[172]="470906"},[348]={[175]="086506"},[627]={[1073]="312234316224326222328232"},[775]={[140]="332646336652",[141]="332650334636338648"}}

DataModule:RegisterPetData(petData)
