--[[
    Copyright (C) 2023-2026 GurliGebis

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
]]

local BattlePetCompletionist = LibStub("AceAddon-3.0"):GetAddon("BattlePetCompletionist")
if not BattlePetCompletionist then
    return
end

local DataModule = BattlePetCompletionist:GetModule("DataModule")

-- PLEASE DO NOT CHANGE THIS FILE DIRECTLY - UPDATE THE JSON FILE IN GIT AND CREATE A PULL REQUEST INSTEAD --
-- THIS FILE IS GENERATED BY RUNNING THE Update-PetData.ps1 SCRIPT. --

local petData = {[1]={[200]="518418"},[7]={[200]="470598"},[10]={[235]="628202"},[18]={[84]="381577589504617577",[200]="614530"},[27]={[200]="540508"},[37]={[200]="430652"},[50]={[239]="672314"},[52]={[84]="562318"},[56]={[238]="699291"},[57]={[200]="556512"},[70]={[232]="491175"},[78]={[237]="689612"},[84]={[227]="606622",[254]="606622"},[85]={[227]="592522",[254]="592522"},[94]={[200]="476472"},[97]={[200]="490512"},[115]={[198]="486756"},[117]={[198]="254586"},[118]={[204]="762192",[205]="763192",[206]="763215",[207]="763212",[209]="753192",[210]="763212",[212]="762192",[213]="763215",[215]="762192",[218]="763215",[229]="762192"},[119]={[194]="546562",[195]="546562",[196]="546562",[197]="546562"},[121]={[234]="732176"},[210]={[241]="426716",[242]="426716"},[627]={[190]="638188",[192]="304224308218310212316220320234326214326222",[193]="495369",[199]="470399",[224]="586396",[225]="494694",[226]="494694",[227]="446460",[236]="586396",[254]="446460"}}

DataModule:RegisterPetData(petData)
